### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by HomeAutoUser** [fhem/Timer#1]
- [x] sollte vermieden werden direkt in die Hash's zu schreiben wenn dafür entsprechende FHEM Perlfunktionen zur Verfügung
Beispiel Attribute. $attr{$name}{'Attribuname'} sollte entsprechend durch CommandAttr() und dazugehörige Bedingungen durch AttrVal() ersetzt werden https://github.com/fhem/Timer/commit/1eb82ec59f95b060cd9b361ed5ccc880dee4a871

- [x] $hash->{STATE} sollte gar nicht gesetzt werden da somit der Userwunsch stateFormat überschrieben wird. Daher IMMER mittels readingsSingleUpdate oder readingsBulkUpdate setzen https://github.com/fhem/Timer/commit/1eb82ec59f95b060cd9b361ed5ccc880dee4a871

- [ ] aktuell versucht neue Module mit package um zu setzen. package sind in Perl das was Klassen unter C++ und Java sind. Es gibt eine Import und Export Funktionen damit man Funktionen anderer Module importieren oder wenn nötig seine eigenen Exportieren kann.

- [x] Aktion reload Browserseite bei SAVE optimieren nach `my $reload = 0;` https://github.com/fhem/Timer/commit/795055262fb4756e23adea623072b45caf18adb7

------------------------------
User request:
- [x] SA / SU - Wert einsichtig (bzw. lesbar irgendwo wiedergegeben)  https://github.com/fhem/Timer/commit/1eb82ec59f95b060cd9b361ed5ccc880dee4a871
- [x] fester Bezug Pfad vom Logfile ersetzen (%L) https://github.com/fhem/Timer/commit/1eb82ec59f95b060cd9b361ed5ccc880dee4a871

Forum https://forum.fhem.de/index.php/topic,103986.msg978726.html#msg978726
- [X] Commandref Beispielcode - Timer alle x-Minuten/Stunde https://github.com/fhem/Timer/pull/3/commits/5675ba99c827993d47189cd550ce375a1852c7a0
- [x] Commandref - Bessere Erläuterung mit * gekennzeichnet, dass Perl Code in ein eigenes Attribut eingetragen werden muss! ggf + Pop-Up oder deutliche Meldung oder Log-Eintrag wenn man Def. auswählt, dass nun ein Attribut mit dem Perl-Code bzw. Fhem-Befehlt angelegt werden muss. https://github.com/fhem/Timer/commit/795055262fb4756e23adea623072b45caf18adb7
- [x] DEF anstatt Def für PERL Code https://forum.fhem.de/index.php/topic,103986.msg978902.html#msg978902 https://github.com/fhem/Timer/commit/795055262fb4756e23adea623072b45caf18adb7
- [X] CSS Farbe Zeilen Tabelle von Styles holen? Nicht fest oder konfigurierbar https://github.com/fhem/Timer/pull/3/commits/5675ba99c827993d47189cd550ce375a1852c7a0
